#!/bin/sh

uci -q batch <<'EOF'
set network.lan.ipaddr='192.168.21.1'
set network.lan.netmask='255.255.255.0'
set system.@system[0].zonename='Asia/Shanghai'
set system.@system[0].timezone='CST-8'
EOF

uci commit network
uci commit system

exit 0
